package entity;
// Generated 11/05/2019 09:38:00 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Operaciones generated by hbm2java
 */
public class Operaciones  implements java.io.Serializable {


     private Integer idop;
     private Usuarios usuarios;
     private String operacion;
     private Date fecha;
     private String filename;

    public Operaciones() {
    }

	
    public Operaciones(Date fecha) {
        this.fecha = fecha;
    }
    public Operaciones(Usuarios usuarios, String operacion, Date fecha, String filename) {
       this.usuarios = usuarios;
       this.operacion = operacion;
       this.fecha = fecha;
       this.filename = filename;
    }
   
    public Integer getIdop() {
        return this.idop;
    }
    
    public void setIdop(Integer idop) {
        this.idop = idop;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public String getOperacion() {
        return this.operacion;
    }
    
    public void setOperacion(String operacion) {
        this.operacion = operacion;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getFilename() {
        return this.filename;
    }
    
    public void setFilename(String filename) {
        this.filename = filename;
    }




}


