package entity;
// Generated 25/04/2019 10:32:57 AM by Hibernate Tools 4.3.1



/**
 * Usuarios generated by hbm2java
 */
public class Usuarios  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private String tipo;
     private String correo;
     private String pass;
     private String permisos;

    public Usuarios() {
    }

    public Usuarios(String nombre, String tipo, String correo, String pass, String permisos) {
       this.nombre = nombre;
       this.tipo = tipo;
       this.correo = correo;
       this.pass = pass;
       this.permisos = permisos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getPass() {
        return this.pass;
    }
    
    public void setPass(String pass) {
        this.pass = pass;
    }
    public String getPermisos() {
        return this.permisos;
    }
    
    public void setPermisos(String permisos) {
        this.permisos = permisos;
    }




}


